package com.platform.dal.model.platform;

import java.io.Serializable;
import java.util.Date;

public class Env implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.id
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.env_name
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private String envName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.url
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.project
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.env_description
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private String envDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.update_at
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.creat_at
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private Date creatAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.id
     *
     * @return the value of env.id
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.id
     *
     * @param id the value for env.id
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.env_name
     *
     * @return the value of env.env_name
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.env_name
     *
     * @param envName the value for env.env_name
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.url
     *
     * @return the value of env.url
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.url
     *
     * @param url the value for env.url
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.project
     *
     * @return the value of env.project
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.project
     *
     * @param project the value for env.project
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.env_description
     *
     * @return the value of env.env_description
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public String getEnvDescription() {
        return envDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.env_description
     *
     * @param envDescription the value for env.env_description
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public void setEnvDescription(String envDescription) {
        this.envDescription = envDescription == null ? null : envDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.update_at
     *
     * @return the value of env.update_at
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.update_at
     *
     * @param updateAt the value for env.update_at
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.creat_at
     *
     * @return the value of env.creat_at
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public Date getCreatAt() {
        return creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.creat_at
     *
     * @param creatAt the value for env.creat_at
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    public void setCreatAt(Date creatAt) {
        this.creatAt = creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", envName=").append(envName);
        sb.append(", url=").append(url);
        sb.append(", project=").append(project);
        sb.append(", envDescription=").append(envDescription);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", creatAt=").append(creatAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}