package com.platform.dal.model.platform;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExecuteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public ExecuteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNull() {
            addCriterion("case_name is null");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNotNull() {
            addCriterion("case_name is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNameEqualTo(String value) {
            addCriterion("case_name =", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotEqualTo(String value) {
            addCriterion("case_name <>", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThan(String value) {
            addCriterion("case_name >", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("case_name >=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThan(String value) {
            addCriterion("case_name <", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThanOrEqualTo(String value) {
            addCriterion("case_name <=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLike(String value) {
            addCriterion("case_name like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotLike(String value) {
            addCriterion("case_name not like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameIn(List<String> values) {
            addCriterion("case_name in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotIn(List<String> values) {
            addCriterion("case_name not in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameBetween(String value1, String value2) {
            addCriterion("case_name between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotBetween(String value1, String value2) {
            addCriterion("case_name not between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdIsNull() {
            addCriterion("interface_id is null");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdIsNotNull() {
            addCriterion("interface_id is not null");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdEqualTo(Integer value) {
            addCriterion("interface_id =", value, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdNotEqualTo(Integer value) {
            addCriterion("interface_id <>", value, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdGreaterThan(Integer value) {
            addCriterion("interface_id >", value, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("interface_id >=", value, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdLessThan(Integer value) {
            addCriterion("interface_id <", value, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdLessThanOrEqualTo(Integer value) {
            addCriterion("interface_id <=", value, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdIn(List<Integer> values) {
            addCriterion("interface_id in", values, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdNotIn(List<Integer> values) {
            addCriterion("interface_id not in", values, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdBetween(Integer value1, Integer value2) {
            addCriterion("interface_id between", value1, value2, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andInterfaceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("interface_id not between", value1, value2, "interfaceId");
            return (Criteria) this;
        }

        public Criteria andProjectIsNull() {
            addCriterion("project is null");
            return (Criteria) this;
        }

        public Criteria andProjectIsNotNull() {
            addCriterion("project is not null");
            return (Criteria) this;
        }

        public Criteria andProjectEqualTo(String value) {
            addCriterion("project =", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotEqualTo(String value) {
            addCriterion("project <>", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThan(String value) {
            addCriterion("project >", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThanOrEqualTo(String value) {
            addCriterion("project >=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThan(String value) {
            addCriterion("project <", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThanOrEqualTo(String value) {
            addCriterion("project <=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLike(String value) {
            addCriterion("project like", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotLike(String value) {
            addCriterion("project not like", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectIn(List<String> values) {
            addCriterion("project in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotIn(List<String> values) {
            addCriterion("project not in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectBetween(String value1, String value2) {
            addCriterion("project between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotBetween(String value1, String value2) {
            addCriterion("project not between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andBodyIsNull() {
            addCriterion("body is null");
            return (Criteria) this;
        }

        public Criteria andBodyIsNotNull() {
            addCriterion("body is not null");
            return (Criteria) this;
        }

        public Criteria andBodyEqualTo(Object value) {
            addCriterion("body =", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotEqualTo(Object value) {
            addCriterion("body <>", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThan(Object value) {
            addCriterion("body >", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThanOrEqualTo(Object value) {
            addCriterion("body >=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThan(Object value) {
            addCriterion("body <", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThanOrEqualTo(Object value) {
            addCriterion("body <=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyIn(List<Object> values) {
            addCriterion("body in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotIn(List<Object> values) {
            addCriterion("body not in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyBetween(Object value1, Object value2) {
            addCriterion("body between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotBetween(Object value1, Object value2) {
            addCriterion("body not between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andResponseIsNull() {
            addCriterion("response is null");
            return (Criteria) this;
        }

        public Criteria andResponseIsNotNull() {
            addCriterion("response is not null");
            return (Criteria) this;
        }

        public Criteria andResponseEqualTo(Object value) {
            addCriterion("response =", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseNotEqualTo(Object value) {
            addCriterion("response <>", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseGreaterThan(Object value) {
            addCriterion("response >", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseGreaterThanOrEqualTo(Object value) {
            addCriterion("response >=", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseLessThan(Object value) {
            addCriterion("response <", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseLessThanOrEqualTo(Object value) {
            addCriterion("response <=", value, "response");
            return (Criteria) this;
        }

        public Criteria andResponseIn(List<Object> values) {
            addCriterion("response in", values, "response");
            return (Criteria) this;
        }

        public Criteria andResponseNotIn(List<Object> values) {
            addCriterion("response not in", values, "response");
            return (Criteria) this;
        }

        public Criteria andResponseBetween(Object value1, Object value2) {
            addCriterion("response between", value1, value2, "response");
            return (Criteria) this;
        }

        public Criteria andResponseNotBetween(Object value1, Object value2) {
            addCriterion("response not between", value1, value2, "response");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultIsNull() {
            addCriterion("case_execute_result is null");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultIsNotNull() {
            addCriterion("case_execute_result is not null");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultEqualTo(String value) {
            addCriterion("case_execute_result =", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultNotEqualTo(String value) {
            addCriterion("case_execute_result <>", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultGreaterThan(String value) {
            addCriterion("case_execute_result >", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultGreaterThanOrEqualTo(String value) {
            addCriterion("case_execute_result >=", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultLessThan(String value) {
            addCriterion("case_execute_result <", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultLessThanOrEqualTo(String value) {
            addCriterion("case_execute_result <=", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultLike(String value) {
            addCriterion("case_execute_result like", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultNotLike(String value) {
            addCriterion("case_execute_result not like", value, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultIn(List<String> values) {
            addCriterion("case_execute_result in", values, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultNotIn(List<String> values) {
            addCriterion("case_execute_result not in", values, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultBetween(String value1, String value2) {
            addCriterion("case_execute_result between", value1, value2, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andCaseExecuteResultNotBetween(String value1, String value2) {
            addCriterion("case_execute_result not between", value1, value2, "caseExecuteResult");
            return (Criteria) this;
        }

        public Criteria andAssertionContentIsNull() {
            addCriterion("assertion_content is null");
            return (Criteria) this;
        }

        public Criteria andAssertionContentIsNotNull() {
            addCriterion("assertion_content is not null");
            return (Criteria) this;
        }

        public Criteria andAssertionContentEqualTo(Object value) {
            addCriterion("assertion_content =", value, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentNotEqualTo(Object value) {
            addCriterion("assertion_content <>", value, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentGreaterThan(Object value) {
            addCriterion("assertion_content >", value, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentGreaterThanOrEqualTo(Object value) {
            addCriterion("assertion_content >=", value, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentLessThan(Object value) {
            addCriterion("assertion_content <", value, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentLessThanOrEqualTo(Object value) {
            addCriterion("assertion_content <=", value, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentIn(List<Object> values) {
            addCriterion("assertion_content in", values, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentNotIn(List<Object> values) {
            addCriterion("assertion_content not in", values, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentBetween(Object value1, Object value2) {
            addCriterion("assertion_content between", value1, value2, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertionContentNotBetween(Object value1, Object value2) {
            addCriterion("assertion_content not between", value1, value2, "assertionContent");
            return (Criteria) this;
        }

        public Criteria andAssertResultIsNull() {
            addCriterion("assert_result is null");
            return (Criteria) this;
        }

        public Criteria andAssertResultIsNotNull() {
            addCriterion("assert_result is not null");
            return (Criteria) this;
        }

        public Criteria andAssertResultEqualTo(String value) {
            addCriterion("assert_result =", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultNotEqualTo(String value) {
            addCriterion("assert_result <>", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultGreaterThan(String value) {
            addCriterion("assert_result >", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultGreaterThanOrEqualTo(String value) {
            addCriterion("assert_result >=", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultLessThan(String value) {
            addCriterion("assert_result <", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultLessThanOrEqualTo(String value) {
            addCriterion("assert_result <=", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultLike(String value) {
            addCriterion("assert_result like", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultNotLike(String value) {
            addCriterion("assert_result not like", value, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultIn(List<String> values) {
            addCriterion("assert_result in", values, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultNotIn(List<String> values) {
            addCriterion("assert_result not in", values, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultBetween(String value1, String value2) {
            addCriterion("assert_result between", value1, value2, "assertResult");
            return (Criteria) this;
        }

        public Criteria andAssertResultNotBetween(String value1, String value2) {
            addCriterion("assert_result not between", value1, value2, "assertResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserIsNull() {
            addCriterion("last_execute_user is null");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserIsNotNull() {
            addCriterion("last_execute_user is not null");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserEqualTo(String value) {
            addCriterion("last_execute_user =", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserNotEqualTo(String value) {
            addCriterion("last_execute_user <>", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserGreaterThan(String value) {
            addCriterion("last_execute_user >", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserGreaterThanOrEqualTo(String value) {
            addCriterion("last_execute_user >=", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserLessThan(String value) {
            addCriterion("last_execute_user <", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserLessThanOrEqualTo(String value) {
            addCriterion("last_execute_user <=", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserLike(String value) {
            addCriterion("last_execute_user like", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserNotLike(String value) {
            addCriterion("last_execute_user not like", value, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserIn(List<String> values) {
            addCriterion("last_execute_user in", values, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserNotIn(List<String> values) {
            addCriterion("last_execute_user not in", values, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserBetween(String value1, String value2) {
            addCriterion("last_execute_user between", value1, value2, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andLastExecuteUserNotBetween(String value1, String value2) {
            addCriterion("last_execute_user not between", value1, value2, "lastExecuteUser");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execute
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 16 16:57:01 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execute
     *
     * @mbg.generated Sun Aug 16 16:57:01 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}