package com.platform.dal.model.platform;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.util.Date;

public class Interface implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.id
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    @JsonIgnore
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.interface_name
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String interfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.project
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.path
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.method
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.mode
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.sign
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private Boolean sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.header
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private Boolean header;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.mock
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private Boolean mock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.description
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.creat_at
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    @JsonIgnore
    private Date creatAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.update_at
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    @JsonIgnore
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.headerDetail
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String headerdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.body
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.id
     *
     * @return the value of interface.id
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.id
     *
     * @param id the value for interface.id
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.interface_name
     *
     * @return the value of interface.interface_name
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.interface_name
     *
     * @param interfaceName the value for interface.interface_name
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.project
     *
     * @return the value of interface.project
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.project
     *
     * @param project the value for interface.project
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.path
     *
     * @return the value of interface.path
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.path
     *
     * @param path the value for interface.path
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.method
     *
     * @return the value of interface.method
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.method
     *
     * @param method the value for interface.method
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.mode
     *
     * @return the value of interface.mode
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.mode
     *
     * @param mode the value for interface.mode
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.sign
     *
     * @return the value of interface.sign
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public Boolean getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.sign
     *
     * @param sign the value for interface.sign
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setSign(Boolean sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.header
     *
     * @return the value of interface.header
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public Boolean getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.header
     *
     * @param header the value for interface.header
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setHeader(Boolean header) {
        this.header = header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.mock
     *
     * @return the value of interface.mock
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public Boolean getMock() {
        return mock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.mock
     *
     * @param mock the value for interface.mock
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setMock(Boolean mock) {
        this.mock = mock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.description
     *
     * @return the value of interface.description
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.description
     *
     * @param description the value for interface.description
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.creat_at
     *
     * @return the value of interface.creat_at
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public Date getCreatAt() {
        return creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.creat_at
     *
     * @param creatAt the value for interface.creat_at
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setCreatAt(Date creatAt) {
        this.creatAt = creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.update_at
     *
     * @return the value of interface.update_at
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.update_at
     *
     * @param updateAt the value for interface.update_at
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.headerDetail
     *
     * @return the value of interface.headerDetail
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getHeaderdetail() {
        return headerdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.headerDetail
     *
     * @param headerdetail the value for interface.headerDetail
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setHeaderdetail(String headerdetail) {
        this.headerdetail = headerdetail == null ? null : headerdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.body
     *
     * @return the value of interface.body
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.body
     *
     * @param body the value for interface.body
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", interfaceName=").append(interfaceName);
        sb.append(", project=").append(project);
        sb.append(", path=").append(path);
        sb.append(", method=").append(method);
        sb.append(", mode=").append(mode);
        sb.append(", sign=").append(sign);
        sb.append(", header=").append(header);
        sb.append(", mock=").append(mock);
        sb.append(", description=").append(description);
        sb.append(", creatAt=").append(creatAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", headerdetail=").append(headerdetail);
        sb.append(", body=").append(body);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}