package com.platform.dal.model.platform;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Plan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.id
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.plan_name
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private String planName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.plan_description
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private String planDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.project
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.env
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private String env;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.plan_content
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private String planContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.plan_execute_result
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private String planExecuteResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.tester
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private String tester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.execute_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date executeAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.update_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.create_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.id
     *
     * @return the value of plan.id
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.id
     *
     * @param id the value for plan.id
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.plan_name
     *
     * @return the value of plan.plan_name
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.plan_name
     *
     * @param planName the value for plan.plan_name
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.plan_description
     *
     * @return the value of plan.plan_description
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public String getPlanDescription() {
        return planDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.plan_description
     *
     * @param planDescription the value for plan.plan_description
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setPlanDescription(String planDescription) {
        this.planDescription = planDescription == null ? null : planDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.project
     *
     * @return the value of plan.project
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.project
     *
     * @param project the value for plan.project
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.env
     *
     * @return the value of plan.env
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.env
     *
     * @param env the value for plan.env
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.plan_content
     *
     * @return the value of plan.plan_content
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public String getPlanContent() {
        return planContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.plan_content
     *
     * @param planContent the value for plan.plan_content
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setPlanContent(String planContent) {
        this.planContent = planContent == null ? null : planContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.plan_execute_result
     *
     * @return the value of plan.plan_execute_result
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public String getPlanExecuteResult() {
        return planExecuteResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.plan_execute_result
     *
     * @param planExecuteResult the value for plan.plan_execute_result
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setPlanExecuteResult(String planExecuteResult) {
        this.planExecuteResult = planExecuteResult == null ? null : planExecuteResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.tester
     *
     * @return the value of plan.tester
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public String getTester() {
        return tester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.tester
     *
     * @param tester the value for plan.tester
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setTester(String tester) {
        this.tester = tester == null ? null : tester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.execute_at
     *
     * @return the value of plan.execute_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public Date getExecuteAt() {
        return executeAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.execute_at
     *
     * @param executeAt the value for plan.execute_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setExecuteAt(Date executeAt) {
        this.executeAt = executeAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.update_at
     *
     * @return the value of plan.update_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.update_at
     *
     * @param updateAt the value for plan.update_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.create_at
     *
     * @return the value of plan.create_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.create_at
     *
     * @param createAt the value for plan.create_at
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", planName=").append(planName);
        sb.append(", planDescription=").append(planDescription);
        sb.append(", project=").append(project);
        sb.append(", env=").append(env);
        sb.append(", planContent=").append(planContent);
        sb.append(", planExecuteResult=").append(planExecuteResult);
        sb.append(", tester=").append(tester);
        sb.append(", executeAt=").append(executeAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", createAt=").append(createAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}