package com.platform.dal.model.platform;

import java.io.Serializable;
import java.util.Date;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_description
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private String projectDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_module
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private String projectModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.tester
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private String tester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.is_valid
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_at
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_at
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_description
     *
     * @return the value of project.project_description
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_description
     *
     * @param projectDescription the value for project.project_description
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription == null ? null : projectDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_module
     *
     * @return the value of project.project_module
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public String getProjectModule() {
        return projectModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_module
     *
     * @param projectModule the value for project.project_module
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setProjectModule(String projectModule) {
        this.projectModule = projectModule == null ? null : projectModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.tester
     *
     * @return the value of project.tester
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public String getTester() {
        return tester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.tester
     *
     * @param tester the value for project.tester
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setTester(String tester) {
        this.tester = tester == null ? null : tester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.is_valid
     *
     * @return the value of project.is_valid
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.is_valid
     *
     * @param isValid the value for project.is_valid
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_at
     *
     * @return the value of project.update_at
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_at
     *
     * @param updateAt the value for project.update_at
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_at
     *
     * @return the value of project.create_at
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_at
     *
     * @param createAt the value for project.create_at
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Mon Jul 13 17:00:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectName=").append(projectName);
        sb.append(", projectDescription=").append(projectDescription);
        sb.append(", projectModule=").append(projectModule);
        sb.append(", tester=").append(tester);
        sb.append(", isValid=").append(isValid);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", createAt=").append(createAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}