package com.platform.dal.model.platform;

import java.io.Serializable;
import java.util.Date;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_description
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private String projectDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_module
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private String projectModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.tester
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private String tester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.valid
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_at
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.creat_at
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private Date creatAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_description
     *
     * @return the value of project.project_description
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_description
     *
     * @param projectDescription the value for project.project_description
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription == null ? null : projectDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_module
     *
     * @return the value of project.project_module
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public String getProjectModule() {
        return projectModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_module
     *
     * @param projectModule the value for project.project_module
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setProjectModule(String projectModule) {
        this.projectModule = projectModule == null ? null : projectModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.tester
     *
     * @return the value of project.tester
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public String getTester() {
        return tester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.tester
     *
     * @param tester the value for project.tester
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setTester(String tester) {
        this.tester = tester == null ? null : tester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.valid
     *
     * @return the value of project.valid
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.valid
     *
     * @param valid the value for project.valid
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_at
     *
     * @return the value of project.update_at
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_at
     *
     * @param updateAt the value for project.update_at
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.creat_at
     *
     * @return the value of project.creat_at
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public Date getCreatAt() {
        return creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.creat_at
     *
     * @param creatAt the value for project.creat_at
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    public void setCreatAt(Date creatAt) {
        this.creatAt = creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jul 15 16:36:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectName=").append(projectName);
        sb.append(", projectDescription=").append(projectDescription);
        sb.append(", projectModule=").append(projectModule);
        sb.append(", tester=").append(tester);
        sb.append(", valid=").append(valid);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", creatAt=").append(creatAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}