package com.platform.dal.mapper.platform;

import com.platform.dal.model.platform.Env;
import com.platform.dal.model.platform.EnvExample;
import java.util.List;

import io.swagger.annotations.ApiParam;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Select;

public interface EnvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    long countByExample(EnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int deleteByExample(EnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int insert(Env record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int insertSelective(Env record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    List<Env> selectByExample(EnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    Env selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Env record, @Param("example") EnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int updateByExample(@Param("record") Env record, @Param("example") EnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int updateByPrimaryKeySelective(Env record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated Sat Jul 18 22:29:44 CST 2020
     */
    int updateByPrimaryKey(Env record);

    /***
     * 分页查询
     */
    List<Env>  queryPage(@Param("pageNum") int pageNum,@Param("pageSize") int pageSize,@ApiParam(value ="envName") String envName);

    /***
     * 查询测试环境总数
     */
    int queryEnvTotal();

    /***
     * 批量删除环境
     */
    void deletes(int[] ids);

    /***
     * 查询环境详情
     * @return
     */
    List<Env> queryEnv();

    /***
     * 根据环境名称查询环境IP
     * @param envName
     */
    String queryPathByEnvName(String envName);
}