package com.platform.dal.mapper.platform;

import com.platform.dal.model.platform.Execute;
import com.platform.dal.model.platform.ExecuteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExecuteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    long countByExample(ExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int deleteByExample(ExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int insert(Execute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int insertSelective(Execute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    List<Execute> selectByExample(ExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    Execute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") Execute record, @Param("example") ExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int updateByExample(@Param("record") Execute record, @Param("example") ExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int updateByPrimaryKeySelective(Execute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execute
     *
     * @mbg.generated Mon Aug 17 13:11:43 CST 2020
     */
    int updateByPrimaryKey(Execute record);

    /***
     * 查询所有用例
     */
    List<Execute> queryPage(int pageNum,int pageSize,String caseName);

    /***
     * 查询用例总数
     */
    int queryCaseTotal();

    /***
     * 通过用例名称查询用例详情
     * @param caseName
     */
    Execute selectByCaseName(String caseName);
}