package com.platform.dal.mapper.platform;

import com.platform.dal.model.platform.Interface;
import com.platform.dal.model.platform.InterfaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    long countByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int deleteByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int insert(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int insertSelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    List<Interface> selectByExampleWithBLOBs(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    List<Interface> selectByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    Interface selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Interface record, @Param("example") InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Interface record, @Param("example") InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int updateByExample(@Param("record") Interface record, @Param("example") InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int updateByPrimaryKeySelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated Tue Jul 21 22:09:34 CST 2020
     */
    int updateByPrimaryKey(Interface record);


    /***
     * 查询所有接口
     */
    int queryInterFaceTotal();

    /***
     * 查询接口列表
     */
    List<Interface> queryPage(int pageNum,int pageSize,String interfaceName);
}