package com.platform.dal.mapper.platform;

import com.platform.dal.model.platform.Plan;
import com.platform.dal.model.platform.PlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    long countByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int deleteByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    List<Plan> selectByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    Plan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") Plan record, @Param("example") PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int updateByExample(@Param("record") Plan record, @Param("example") PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan
     *
     * @mbg.generated Sun Oct 18 11:24:58 CST 2020
     */
    int updateByPrimaryKey(Plan record);

    /***
     * 分页查询
     */
    List<Plan> queryPage(int pageNum,int pageSize,String planName);
}