package com.platform.dal.mapper.platform;

import com.platform.dal.model.platform.SysRole;
import com.platform.dal.model.platform.SysRoleExample;
import java.util.List;

import com.platform.entity.UserEntity;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.mapping.FetchType;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    long countByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int deleteByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    List<SysRole> selectByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    SysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int updateByPrimaryKey(SysRole record);


    @Select("select id,description,name from sys_role where id = #{id}")
    @Results({
            @Result(id=true,column="id",property="id"),
            @Result(column = "id",property="rolePermission",many = @Many(select = "com.platform.dal.mapper.platform.SysRolePermissionMapper.getRolePermission",fetchType = FetchType.LAZY)),
//            @Result(column = "#{uid}",property = "userEntity",many = @Many(select = "com.platform.dal.mapper.platform.UserMapper.selectByPrimaryKey",fetchType = FetchType.LAZY)),
            @Result(column = "description",property="description"),
            @Result(column = "name",property="name")
    }
    )
    List<com.platform.entity.po.SysRole> getSysRoles(int roleId);
}