package com.platform.dal.mapper.platform;

import com.platform.dal.model.platform.SysRole;
import com.platform.dal.model.platform.SysUserRole;
import com.platform.dal.model.platform.SysUserRoleExample;
import java.util.List;

import com.platform.entity.po.SysUserRolePO;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.mapping.FetchType;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    long countByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int deleteByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int insertSelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    List<SysUserRole> selectByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Wed Jan 20 11:13:55 CST 2021
     */
    int updateByExample(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);


    /***
     * 根据角色名称查询对应的多个用户
     * @param uid
     * @return
     */
    @Select("select role_id,uid from sys_user_role where uid = #{uid}")
    @Results(
            {
                @Result(id=true,column="role_id",property="roleId"),
                @Result(column="role_id",property="SysRoles",many = @Many(select = "com.platform.dal.mapper.platform.SysRoleMapper.getSysRoles",fetchType = FetchType.LAZY)),
    //          @Result(column="uid}",property="SysRoles",many = @Many(select = "com.platform.dal.mapper.platform.SysRoleMapper.getSysRoles",fetchType = FetchType.LAZY)),
                @Result(column="uid",property="uid")
            }
    )
    List<SysUserRolePO> getUserRole(Integer uid);
}